node {

  def frontendImage

  step([$class: 'WsCleanup'])

  stage("Checkout code") {
    checkout scm
  }

  try {
    stage("Execute test") {
    dir('frontend') {
        docker.image('node:10.11.0-alpine').inside {
          withEnv([
              /* Override the npm cache directory to avoid: EACCES: permission denied, mkdir '/.npm' */
              'npm_config_cache=npm-cache',
              /* Override HOME Path */
              'HOME=.'
          ]) {
            sh 'npm install'
            sh 'npm test'
          }
        }
      }
    }
  } catch (e) {

  } finally {
    junit '**/frontend/test-results.xml'
  }

  stage("Execute test") {
    dir('frontend') {
      docker.image('node:10.11.0-alpine').inside {
        withEnv([
            /* Override the npm cache directory to avoid: EACCES: permission denied, mkdir '/.npm' */
            'npm_config_cache=npm-cache',
            /* Override HOME Path */
            'HOME=.'
        ]) {
          sh 'npm install'
          sh 'npm test'
        }
      }
    }
  }

  stage("Build frontend image") {
    dir('frontend') {
      frontendImage = docker.build('manuel11coral23/frontend')
    }
  }

  stage("Push image to registry") {
    docker.withRegistry('', 'docker-hub') {
      frontendImage.push()
    }
  }

}